spring:
  datasource:
    url: jdbc:mysql://
    username: admin
    password: admin1234
  jpa:
   show-sql: true
   hibernate:
    ddl-auto: update
    naming:
     physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
   properties:
    hibernate:
     dialect: org.hibernate.dialect.MySQL8Dialect