spring:
  datasource:
    url: jdbc:mysql://database-2.cram5uzdzwue.us-east-1.rds.amazonaws.com
    username: admin
    password: doraemon
  jpa:
   show-sql: true
   hibernate:
    ddl-auto: update
    naming:
     physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
   properties:
    hibernate:
     dialect: org.hibernate.dialect.MySQL8Dialect
